apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-ext-secrets
  namespace: autobots
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: wowee
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: swag
