apiVersion: v1
kind: Secret
metadata:
  name: ${NAME}
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: ${NAME}
  server: ${SERVER}
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData": "${CA_DATA}",
        "certData": "${CERT}",
        "keyData": "${KEY}"
      }
    }